apiVersion: 1
datasources:
  - name: Krabka Metrics
    uid: krabka-prom
    type: prometheus
    access: proxy
    url: http://metrics-querier:9090
    isDefault: true
    jsonData:
      httpHeaderName1: X-Scope-OrgID
    secureJsonData:
      httpHeaderValue1: demo
    editable: false
  - name: Krabka Traces
    uid: krabka-tempo
    type: tempo
    access: proxy
    url: http://traces-querier:3200
    jsonData:
      httpMethod: GET
      httpHeaderName1: X-Scope-OrgID
    secureJsonData:
      httpHeaderValue1: demo
    editable: false
  - name: Krabka Logs
    uid: krabka-loki
    type: loki
    access: proxy
    url: http://logs-querier:3100
    jsonData:
      httpHeaderName1: X-Scope-OrgID
      manageAlerts: false
      maxLines: 100
    secureJsonData:
      httpHeaderValue1: demo
    editable: false
  - name: Krabka Profiles
    uid: krabka-pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://profiles-querier:4040
    jsonData:
      httpHeaderName1: X-Scope-OrgID
    secureJsonData:
      httpHeaderValue1: demo
    editable: false
